---
 - name: Add Nginx repository
   apt_repository: repo='ppa:nginx/stable' state=present
   tags:
    - repo
    - nginx

 - name: Install Nginx
   apt: pkg=nginx state=installed update_cache=true
   notify:
     - Start Nginx
   tags:
     - nginx

 - name: Copy H5BP Config
   copy: src=h5bp dest=/etc/nginx/ owner=root group=root
   tags:
     - nginx

 - name: Disable Default Config
   file: dest=/etc/nginx/sites-enabled/default state=absent
   notify:
   - Reload Nginx
   tags:
     - nginx

 - name: Add BB Site Config
   template: src={{ domain }}.j2 dest=/etc/nginx/sites-available/{{ domain }} owner=root group=root
   tags:
     - nginx

 - name: Enable BB Site Config
   file: src=/etc/nginx/sites-available/{{ domain }} dest=/etc/nginx/sites-enabled/{{ domain }} state=link
   tags:
     - nginx

