---
 - name: Creating kibana group
   group: name=kibana gid=999 state=present
   register: kibanagroupok
   tags:
    - users
    - kibana

 - name: Creating kibana user
   user: name=kibana uid=999 group=kibana
   when: kibanagroupok|success
   register: kibanauserok

 - name: Creating directory for Kibana
   file: path=/opt/kibana state=directory mode=0755 owner=kibana group=kibana
   when: kibanauserok|success
   register: kibanadirok
